server:
  port: 8081
  servlet:
    session:
      timeout: 3600s

spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.35.45.30:3306/graduationdb?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true&serverTimezone=UTC
    username: user
    password: 233233
    hikari:
      max-lifetime: 180000

mybatis:
  mapper-locations: classpath:mapper/*.xml

shiro:
  secret: f4e2e52034348f86b67cde581c09eb5
  expire: 604800
  header: Authorization

my:
  filepath: C:\Users\13999\Desktop\MyFile\


logging:
  level:
    com.ljsh.test.domain.mapper: debug